name: fast-reverse-proxy
version: 0.52.3
summary: fast reverse proxy
description: fast reverse proxy
adopt-info: configs

base: core24
confinement: strict
grade: stable

platforms:
  amd64:
  arm64:
  armhf:

apps:
  frps:
    command: bin/frps -c $SNAP_DATA/frps.toml
    daemon: simple
    plugs: [network, network-bind]
  frpc:
    command: bin/frpc -c $SNAP_DATA/frpc.toml
    daemon: simple
    plugs: [network, network-bind]

parts:
  frp:
    plugin: go
    source: https://github.com/fatedier/frp.git
    source-tag: v0.52.3
    # build-environment:
    #   - GOPROXY: https://proxy.golang.com.cn,direct
    build-snaps:
      - go
  configs:
    plugin: dump
    source: configs
    source-type: local
    override-stage: |
      craftctl default
      craftctl set version="$(craftctl get version)-$(git rev-parse --short HEAD)"
